### ISSUE TITLE
docker issues

### ISSUE THREAD

**Issue by dhlsam** [Woolverine94/biniou#13]
after using cuda docker Dockerfile to build images,there is syntaxerror in controlnet.py file

docker run -it --gpus all --restart=always -p 7870:7860 \
-v /mnt/user/ai/biniou/outputs:/home/biniou/biniou/outputs \
-v /mnt/user/ai/biniou/models:/home/biniou/biniou/models \
-v /mnt/user/ai/biniou/cache:/home/biniou/.cache/huggingface \
-v /mnt/user/ai/biniou/gfpgan:/home/biniou/biniou/gfpgan \
biniou:latest

Traceback (most recent call last):
  File "/home/biniou/biniou/webui.py", line 14, in <module>
    from ressources import *
  File "/home/biniou/biniou/ressources/__init__.py", line 21, in <module>
    from .controlnet import *
  File "/home/biniou/biniou/ressources/controlnet.py", line 137
    match preprocessor_controlnet:
               ^
SyntaxError: invalid syntax

**Comment by Woolverine94** [comment]
Hello @dhlsam,

Can you please give more information on your setup ? 

I've already encountered this error, but with outdated  python version (>3.10 as match statement was introduced in python 3.10).
