### ISSUE TITLE
Windows 11 documentation

### ISSUE THREAD

**Issue by Tobe2d** [Woolverine94/biniou#18]
I want to test out Biniou however, I am afraid to run biniou_netinstall.exe based on the warning you have on the instructions as I dont want to mess with my windows, 
I need to install it using venv myself and i need clear instruction.

I've tried installing it figuring out the dependancies but now I am stuck on this error:

```
(venv) E:\Ai__Project\biniou>python webui.py
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
>>>[biniou 🧠]: Up and running at https://192.168.1.73:7860/?__theme=dark
Exception in thread Thread-4 (run):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Ai__Project\biniou\venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Ai__Project\biniou\venv\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "E:\Ai__Project\biniou\venv\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "E:\Ai__Project\biniou\venv\Lib\site-packages\uvicorn\config.py", line 399, in load
    self.ssl: ssl.SSLContext | None = create_ssl_context(
                                      ^^^^^^^^^^^^^^^^^^^
  File "E:\Ai__Project\biniou\venv\Lib\site-packages\uvicorn\config.py", line 112, in create_ssl_context
    ctx.load_cert_chain(certfile, keyfile, get_password)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "E:\Ai__Project\biniou\webui.py", line 9668, in <module>
    demo.queue(concurrency_count=8).launch(
  File "E:\Ai__Project\biniou\venv\Lib\site-packages\gradio\blocks.py", line 2033, in launch
    ) = networking.start_server(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai__Project\biniou\venv\Lib\site-packages\gradio\networking.py", line 207, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 7860-7860. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.

(venv) E:\Ai__Project\biniou>
```

**Comment by Woolverine94** [comment]
Hello @Tobe2d,

First for all, thanks for your feedback and your interest in biniou. 

Bad news are biniou doesn't really have any kind of documentation for manual installation under Windows and there is zero chances you can make it work without installing prerequisites. The main risk of installing these prerequisites is breaking a possible existing development environment and/or updating/downgrading a version of a software already installed on your system (note that biniou itself is harmless for your computer, as it uses its own python virtual environment). There is 99.99% of chances that the installation of biniou doesn't impact stability of your system, but I can't honestly guarantee that there would be no problems without knowing your environment, and prefer to warn users about this. 

Good news is that `biniou_netinstall.exe` is nothing more than a downloader for [install_win.cmd](https://raw.githubusercontent.com/Woolverine94/biniou/main/install_win.cmd), which is the true installer. You can (which was maybe what you already did ?), use it as an (almost) self-explanatory step-by-step installer. 

Concerning the error sent back by biniou, it seems that 

>  File "E:\Ai__Project\biniou\venv\Lib\site-packages\uvicorn\config.py", line 399, in load
    self.ssl: ssl.SSLContext | None = create_ssl_context(
                                      ^^^^^^^^^^^^^^^^^^^
  File "E:\Ai__Project\biniou\venv\Lib\site-packages\uvicorn\config.py", line 112, in create_ssl_context
    ctx.load_cert_chain(certfile, keyfile, get_password)
FileNotFoundError: [Errno 2] No such file or directory

indicate that no SSL certificates were found, which is perfectly logical if you haven't installed openssl which is required for generating a certificate at install time. 

If you're still concerned about the security of your system -which is perfectly legitimate !- , I can recommend you to : 
  - Make a backup of your datas and system before installing 
  - Install biniou in a virtual machine (no GPU optimizations)
  - Use one of the two dockerfile provided (CPU or CUDA)

I close this issue, as I assume that the content of install_win.cmd will permits you to install biniou manually, but don't hesitate to re-open it if you encounter a specific issue during installation.
