### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_cpp'

### ISSUE THREAD

**Issue by woehrer12** [Woolverine94/biniou#26]
**Describe the bug**
I installed it with docker on an ubuntu 22 server
Then i get this error

`
>>>[biniou 🧠]: Detected TCMalloc_minimal installation : using it.
Traceback (most recent call last):
  File "/home/biniou/biniou/webui.py", line 14, in <module>
    from ressources import *
  File "/home/biniou/biniou/ressources/__init__.py", line 2, in <module>
    from .llamacpp import *
  File "/home/biniou/biniou/ressources/llamacpp.py", line 3, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
`

**Comment by Woolverine94** [comment]
Hello @woehrer12,

Thanks for your feedback and your interest in biniou.

It complains about not finding llama-cpp-python package. 
It was probably not installed during building of the container image.

Could you :
  - Precise which Dockerfile you were using to build the container image (regular one or CUDA)
  - Confirm that you didn't modify the aformentioned Dockerfile
  - Precise if you're running Docker inside a virtual environment
  - Retry to create a container image using : 

CPU-only :

```bash
docker build --no-cache --progress=plain -t biniou https://github.com/Woolverine94/biniou.git 2>&1 | tee build.log
```
CUDA :

```bash
docker build --no-cache --progress=plain -t biniou https://raw.githubusercontent.com/Woolverine94/biniou/main/CUDA/Dockerfile 2>&1 | tee build.log
```
and post here the build.log content ?

**Comment by woehrer12** [comment]
I used this for the installation:
https://github.com/Woolverine94/biniou#dockerfile

It runs as a virtual maschine as a CT on Proxmox. Its a Ubuntu 22 and on this is docker installed.

[build.log](https://github.com/user-attachments/files/16118107/build.log)

**Comment by Woolverine94** [comment]
Thanks for your answer @woehrer12.

I don't get it. There's no error in your log. 

Llama-cpp-python seems to be installed and should be working. 

Installing the Dockerfile inside a virtual machine can sometimes provoke errors at compilation time of llama-cpp-python, but that doesn't seems to be the case here. 

- Did the new image that generates the log you posted throws the same error ?
- Can you confirm that your architecture is : Proxmox VE hypervisor ->  Ubuntu 22.04 VM hosted on Proxmox -> Docker hosted in the Ubuntu 22.04 VM ?
- Can you post the result of `cat /etc/os-release && uname -a && lsb_release --all` in the Ubuntu 22.04 VM ?

**Comment by Woolverine94** [comment]
Closing this issue as there has been no updates for more than a month.

Please don't hesitate to re-open it if required.
