### ISSUE TITLE
Multiple LoRAs

### ISSUE THREAD

**Issue by Captain-Bacon** [Woolverine94/biniou#34]
At present I can't seem to see a way to have multiple LoRAs when creating an image using SD.... please let me know if I'm just being blind, and if not would it be possible to have the ability to add more?

**Comment by Woolverine94** [comment]
Hello @Captain-Bacon,

Thanks for your interest in the project. 

I can confirm that biniou can only handle a single LoRA currently. 

I flag this issue as an enhancement, as it's completely something feasible, but it will take some times and it is not a priority on the roadmap.

**Comment by Woolverine94** [comment]
Hello @Captain-Bacon,

Following your request, commit 93cc96a introduces experimental support for multiples LoRA (up to 5), only for Stable Diffusion module for now. 

I'll extend it to other Stable Diffusion-based modules, but it will takes some times.

Please note that Fast LoRA models will only appears in the initial LoRA model menu, as they require a specific processing and it would be incoherent to select more than one. All other models are available from all LoRA models lists. 

Please also note that more LoRA could means more inferences steps, depending of the models and of the LoRAs, and it is almost impossible to handle it automatically. 

I close this issue as your initial request should now be satisfied.

**Comment by Woolverine94** [comment]
Hello @Captain-Bacon,

Following your request, commit 93cc96a introduces experimental support for multiples LoRA (up to 5), only for Stable Diffusion module for now. 

I'll extend it to other Stable Diffusion-based modules, but it will takes some times.

Please note that Fast LoRA models will only appears in the initial LoRA model menu, as they require a specific processing and it would be incoherent to select more than one. All other models are available from all LoRA models lists. 

Please also note that more LoRA could means more inferences steps, depending of the models and of the LoRAs, and it is almost impossible to handle it automatically. 

I close this issue as your initial request should now be satisfied.
