### ISSUE TITLE
Fedora 39 Install with CUDA missing import. 

### ISSUE THREAD

**Issue by makeitnotfakeit** [Woolverine94/biniou#41]
Getting a import error (fixed direct), used your suggested term install shell script. Did not docker or anything different. When to change over the globe settings to utilize CUDA and got an import error: 

> " Failed to build llama-cpp-python
> ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (llama-cpp-python)
> Traceback (most recent call last):
>   File "/home/bendozer/biniou/webui.py", line 14, in <module>
>     from ressources import *
>   File "/home/bendozer/biniou/ressources/__init__.py", line 1, in <module>
>     from .common import *
>   File "/home/bendozer/biniou/ressources/common.py", line 9, in <module>
>     import torch
>   File "/home/bendozer/biniou/env/lib64/python3.11/site-packages/torch/__init__.py", line 26, in <module>
>     from ._utils import _import_dotted_name, classproperty
> ModuleNotFoundError: No module named 'torch._utils'" 
> 
> Understand how you wouldn't want to install library as standard. Possibly add it as a 'switch'/'modifier' for GPU. 

Else:
##### **Think we all owe you an 'IOU'**
I typically work hardware (PCB/CCA and up) but with the rapid growth in LLM, this is making me want to develop my developer side of my brain a bit rather than making python tools here and there todo all the hard jobs the lazy way. 
Cheers!
Bendozer

**Comment by Woolverine94** [comment]
Hello @makeitnotfakeit,

Thanks for your report and your interest in the project. 

Can you confirm that you get this error when choosing the llama-cpp-python CUDA optimization in the WebUI Settings ? 

If it's the case, I can hardly help you debugging this currently : 

  - I don't have access to CUDA hardware
  - I don't have access to fedora at this time
  - Nobody ever confirmed that the "CUDA for llama" optimization on biniou was working (it's completely theoretical and based on the llama-cpp-python documentation). 

Anyway, you can repair your installation by : 

  - deleting the content of biniou/.ini/llamacpp_backend.cfg (do not delete the file, only the content)
  - launch either update.sh (if you're using CPU inference) or update_cuda.sh (if you want to use CUDA optimization for other modules than chatbot). 

Only workaround I can suggest at this time is switching the acceleration to Vulkan for llama : at least, it should work if vulkan is installed on your system as this is what I use. 

I'll try to have a look at the llama-cpp-python documentation to find if there's a workaround, but I can't test the fix that I'll propose you, so don't have too much expectations. 

> @Woolverine94: Love what you have done with the place.
> Think we all owe you an 'IOU'

Thanks a lot for this appreciation of my work ! Greatly appreciated :)

**Comment by natlamir** [comment]
CUDA wasn't being utilized for me with llama text chat. I am on Windows.
I had to install llama-cpp-python for my installed cuda toolkit version like this:

`pip install --no-cache-dir --force-reinstall llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu123 numpy==1.25.2`

And then change the call to Llama() to include gpu params:

```
llm = Llama(model_path=modelid_llamacpp, seed=seed_llamacpp, n_gpu_layers=-1, n_threads=multiprocessing.cpu_count(), n_threads_batch=multiprocessing.cpu_count(), n_ctx=n_ctx_llamacpp)
```

And now GPU is utlized over 90% and inference is much faster.
Thanks for making this app, it has a lot of useful stuff!

**Comment by Woolverine94** [comment]
@natlamir,

Thanks a lot for the tip ! 

I'll try to adapt my code for CUDA users following your instructions.

**Comment by Woolverine94** [comment]
@natlamir, @makeitnotfakeit,

Using code provided by @natlamir, I've modified the update scripts for use of CUDA 12.1 (please note that this is mandatory to have a CUDA 12.1 environment if you want to use all modules provided by biniou). 

Commit 77913d4 introduces these modifications. 

@natlamir : Thanks again. Using a compiled wheel instead of compiling llama-cpp-python is a much better way to handle it -especially on Windows-. Also, can you confirm there's a real benefit of adding n_threads detected by multiprocessing (CPU inferences are up to 4 times slower on my system when using this) ?

If anyone reading this thread and having access to a CUDA environment can confirm that it solves the issue, it would be great, cause I can't check it myself.

**Comment by natlamir** [comment]
@Woolverine94 Interesting, I found this reddit thread discussion about llama.cpp thread count optimization and how the performance got worse, the higher the thread counts: https://www.reddit.com/r/LocalLLaMA/comments/14djns5/llamacpp_and_thread_count_optimization/

Can probably remove that if it is faster without it. I will try to test it out in my local some time this week with CUDA and will let you know what I find.

Also, I think similar CUDA optimization can be made to the LLAVA module.

Thanks!

**Comment by Woolverine94** [comment]
@natlamir,

Thanks for the tip ! 

> Also, I think similar CUDA optimization can be made to the LLAVA module

Yes, you're right ! I completely forgot that llava model can also be optimized by your tip ! 

I'll give it a look asap. 

Thanks again !

**Comment by natlamir** [comment]
I just tested using only  n_gpu_layers=-1 and it is still utilizing CUDA. Looks like both n_threads and n_threads_batch are not needed, getting the same performance improvements at least on my machine with just n_gpu_layers.

I installed CUDA toolkit 12.1 from the NVIDIA site, then selected CUDA for biniou and GPU for llama in the biniou settings, and it is utilizing CUDA for me. Thanks!

**Comment by Woolverine94** [comment]
@natlamir,

Thanks for your tests and your confirmations ! 

If there's no differences with or without n_threads arguments when using CUDA, i'll leave it as it may be only a problem when using cpu inferences.  

Also, commit 1c91525 introduces your modifications for the llava module. 

A big thanks to you !
