### ISSUE TITLE
Black images even with Safety checker turned off

### ISSUE THREAD

**Issue by Bortus-AI** [Woolverine94/biniou#45]
Getting returned black images when using a few models in stable diffusion. Fluently-XL-Final is one of them as well as Interdiffusion 4.0.
 I have NSFW filter turned off but makes no difference. Biniou output does not show the typical NSFW line saying it was blocked but images are are black which I have only had happen when NSFW filter is on.

**Comment by Bortus-AI** [comment]
After further testing it looks to be working. Shift F5 in Chrome and then disabling again seems to have fixed it.

**Comment by Woolverine94** [comment]
Hello @Bortus-AI,

Note that if you relaunch biniou without refreshing the UI, you can encounter this behavior, as the NSFW filter is reinitialized to True, but as the interface is not refreshed, it's still appears as False in the WebUI controlpanel.
