### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by morbificagent** [Woolverine94/biniou#51]
Hi there,

wanted to try the docker version with the command

docker run -it --restart=always -p 7860:7860 \
-v biniou_outputs:/home/biniou/biniou/outputs \
-v biniou_models:/home/biniou/biniou/models \
-v biniou_cache:/home/biniou/.cache/huggingface \
-v biniou_gfpgan:/home/biniou/biniou/gfpgan \
biniou:latest

But i get this error message:

Traceback (most recent call last):
  File "/home/biniou/biniou/webui.py", line 10, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

**Comment by morbificagent** [comment]
Oh im sorry, i think its because im on ARM :-(

**Comment by Woolverine94** [comment]
Hello @morbificagent,

Thanks for you report. 

Unfortunately, ARM architecture are not indeed supported by biniou (most requirements doesn't provide binaries for ARM architecture). 

If you're using Apple silicon, you can read [this thread](https://github.com/Woolverine94/biniou/issues/42) that provides an acceptable workaround.
