### ISSUE TITLE
Save models locally

### ISSUE THREAD

**Issue by freelancer2000** [Woolverine94/biniou#56]
From what I can see, all files are saved as blobs/snapshots of cache files. Is it possible to make it save locally all files so that the cache folder (which contains also from other python apps snapshots) be removed and not have all files be saved again? Or maybe there is a command line/config argument that might help with this?

**Comment by Woolverine94** [comment]
Hello @freelancer2000,

Thanks for your interest in the project and opening this issue.

In fact, every models ***should*** be saved in the ./models directory of the biniou dir by default, via the `cache_dir` argument of the pipelines (which is more or less what you are referring to as a config argument).

Unfortunately, biniou's dependencies downloads models they requires directly in the cache dir, but it's not something I can control for all types of installs without modifying the code of these dependencies, which is definitely not something desirable. Also, not all pipelines handles the `cache_dir` argument.

But by default,  I always try to use the ./models directory as the default download dir, which is not always feasible.

Thanks again for reporting this issue, but there's not much that can be done about this.
